repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      stages: [commit]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11
      stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v ./src/tests
      always_run: true
      pass_filenames: false
      stages: [commit]
-   repo: local
    hooks:
      - id: dependencies
        name: dependencies
        entry: git add pyproject.toml poetry.lock
        language: system
        pass_filenames: false
        stages: [commit]
