version: '3.8'

services:
  web:
    build: ./
    command: python ./src/django_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
